menu:
    主站: https://osc.shu.edu.cn
    镜像站: /
    官方博客: https://blog.shuosc.org
    所有通知: /news/archives

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /logo.png

# Comment
changyan: bubuzou
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

